language: cpp

sudo: false

compiler:
  - gcc

env:
  matrix:
    - COMPILER=g++-4.8 CCOMPILER=gcc-4.8
    - COMPILER=g++-4.9 CCOMPILER=gcc-4.9
    - COMPILER=g++-5 CCOMPILER=gcc-5
    - COMPILER=g++-6 CCOMPILER=gcc-6
    - COMPILER=clang++-3.6 CCOMPILER=clang-3.6
    - COMPILER=clang++-3.7 CCOMPILER=clang-3.7

matrix:
  allow_failures:
    - COMPILER=g++-4.8 CCOMPILER=gcc-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
    packages:
      - g++-4.8
      - g++-4.9
      - g++-5
      - g++-6
      - g++-6.2
      - clang-3.6
      - clang-3.7
      - clang-3.8
      - valgrind
      - python-pip
      - python-yaml

before_script:
  - export CXX=$COMPILER CC=$CCOMPILER
  - cmake --version
  - mkdir build
  - cd build
  - cmake -LAH ..

script:
  - make VERBOSE=1
